project:
  type: website

website:
  title: "lec_flow_push"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "preprocessing"
        menu:
          - code/preprocessing_n_removal.ipynb
      - text: "Differential expression"
        menu:
          - code/vis_de.qmd
      - text: "Interactively"
        menu:
          - code/shinycell.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

